name = "sub-worker"
main = "_worker.js"
compatibility_date = "2025-07-23"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "110fd615d2c54c608e6979aa1307f4d1"					#KV据库id
